[project]
name = "mopidyir"
description = "Mopidy callbacks to IR events"
version = "0.2.0"
authors = [{ name = "Matthias Meulien <orontee@gmail.com>", email = "orontee@gmail.com"}]
license = "GPL-3.0"
requires-python = ">= 3.13"
dependencies = [
       "evdev >= 1.9",
       "aiohttp >= 3.11",
       "pyyaml >= 6.0.2"
]

[project.scripts]
mopidyir = "mopidyir:main"

[dependency-groups]
dev = [
    "pycodestyle >= 2.12",
    "mypy >= 1.15",
    "black >= 23.12"
]

[build-system]
requires = ["setuptools >= 78"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
