[tool.poetry]
name = "argosir"
version = "0.1.0"
description = "Callback to IR events on argos"
authors = ["Matthias Meulien <orontee@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
evdev = "^1.3.0"
aiohttp = "^3.6.2"

[tool.poetry.dev-dependencies]
pycodestyle = "^2.6.0"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
