[tool.poetry]
name = "argosir"
version = "0.1.0"
description = "Callback to IR events on argos"
authors = ["Matthias Meulien <orontee@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.9.2"
evdev = "^1.3.0"
aiohttp = "^3.8.5"

[tool.poetry.dev-dependencies]
pycodestyle = "^2.6.0"
mypy = "^1.6.0"
black = "^23.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
